### ISSUE TITLE
Have to reconnect after waking the computer

### ISSUE THREAD

**Issue by mkono87** [PiotrMachowski/Home-Assistant-Taskbar-Menu#23] opened 2021-11-10 21:53 UTC
I put my desktop to sleep every night. I noticed after waking it and right click the icon, I have to reconnect first before I can use it. Just curious what the cause of this could be.

**Comment by PiotrMachowski** [comment] 2021-11-10 22:38
The cause is that websocket connection to HA is acting in a wonky way. I haven't found a way to fix it completely yet.

Duplicate of #19

**Closed by PiotrMachowski** 2021-11-10 22:38 UTC
